[versions]
kotlin = "2.1.20"
shadow = "9.0.0-beta15"
serialization = "1.8.1"
telegram = "8.3.0"
coroutines = "1.10.2"
ktor = "3.1.3"
adventure = "4.21.0"
kache = "2.1.1"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

telegram = { module = "com.github.pengrad:java-telegram-bot-api", version.ref = "telegram" }

ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }

kache = { module = "com.mayakapps.kache:kache", version.ref = "kache" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }